# Copyright (c) 2016-2022 Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# build: off

branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+\.\d+$/
  - /^release-\d+\.\d+\.\d+$/
  - /^feature-ci-.+$/
  - /^feature_ci_.+$/

pull_requests:
  do_not_increment_build_number: true

platform:
  - x64

configuration:
  - Release

nuget:
  disable_publish_on_pr: true

environment:
    PYTHON: "C:\\Python37"
    PYTHON_VERSION: "3.7.3"
    PYTHON_ARCH: "32"
    NUGET_API_KEY:
      secure: 2S142WOoAx6CLvTPl0LxBL3PNgbaHTvZwef0KCY0G9dHw2Uw6rnwLiC6vbwZZvlZ

    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PUBLISH_TO_NUGET: "true"

assembly_info:
  patch: false

# init:
  # - ps: |
  #     if ($Env:APPVEYOR_REPO_BRANCH -ceq "master" -And [string]::IsNullOrEmpty($Env:APPVEYOR_REPO_TAG_NAME)) {
  #       Write-Host $Env:APPVEYOR_REPO_BRANCH
  #       Write-Host "branch is master without tags, exiting"
  #       Exit-AppveyorBuild
  #     }

install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%;
  - "python --version"
  - python -m pip install --upgrade pip
  - "%PYTHON%/Scripts/pip.exe install kthbuild --upgrade"

build_script:
  - SET PATH=%PATH%;%PYTHON%/Scripts/
  # - powershell .\build.ps1 -Verbosity diagnostic
  - powershell .\build.ps1 Compile
  - powershell .\build.ps1 Test
  - powershell .\build.ps1 Test

# # test: off
# test:
#   - ps: ./build.ps1 Test

deploy_script:
  - ps: ./build.ps1 Pack
  - ps: ./build.ps1 Push --NugetApiUrl "https://api.nuget.org/v3/index.json" --NugetApiKey $env:NUGET_API_KEY

  # - ps: ./build.ps1 Push --NugetApiUrl "https://www.myget.org/F/cfrenzel-ci/api/v2/package" --NugetApiKey $env:MyGetApiKey
  # - ps: |
  #     if ($env:APPVEYOR_REPO_TAG  -eq "true"){
  #         ./build.ps1 Push --NugetApiUrl "https://api.nuget.org/v3/index.json" --NugetApiKey $env:NUGET_API_KEY
  #     }
